export const portfolioData = [
  {
    id: 1,
    name: "Floppy bird",
    languages: ["JavaScript"],
    languagesIcons: ["fab fa-js"],
    source: "https://github.com/Caronat/floppybird",
    info: "Remake du célèbre jeu flappy bird.\nFaites votre meilleur score.",
    picture: "./media/floppy-bird.JPG",
    link: "https://floppybird.antonycaron.fr",
  },
  {
    id: 2,
    name: "Marvel Quiz",
    languages: ["JavaScript", "React"],
    languagesIcons: ["fab fa-js", "fab fa-react"],
    source: "https://github.com/Caronat/marvel-quiz",
    info: "Une application pour tester vos connaissances sur l'univeres MARVEL.\nVous pourrez même en apprendre plus sur vos personnes préférés via les données de l'API MARVEL.",
    picture: "./media/marvel-quiz.JPG",
    link: "https://marvel-quiz-f8db9.firebaseapp.com/",
  },
  {
    id: 3,
    name: "Movies",
    languages: ["JavaScript", "React"],
    languagesIcons: ["fab fa-js", "fab fa-react"],
    source: "https://github.com/Caronat/movies",
    info: "Utiliser l'API themoviedb pour trouver des films et les ajouter à vos coups de coeur.",
    picture: "./media/movies.JPG",
    link: "https://movies.antonycaron.fr/",
  },
  {
    id: 4,
    name: "Run",
    languages: ["Intégration"],
    languagesIcons: ["fab fa-html5", "fab fa-css3"],
    source: "https://github.com/Caronat/run-integration",
    info: "Exemple d'intégration de site responsive",
    picture: "./media/run.JPG",
    link: "https://run-integration.antonycaron.fr/",
  },
  {
    id: 5,
    name: "G Docs Clone",
    languages: ["JavaScript"],
    languagesIcons: ["fab fa-html5", "fab fa-css3", "fab fa-js"],
    source: "https://github.com/Caronat/g-docs-clone",
    info: "Editeur de texte simple inspiré de Google Docs.\nCette application est construite avec Materialize CSS et Firebase.",
    picture: "./media/g-docs-clone.JPG",
    link: "https://www.g-docs-clone.antonycaron.fr/",
  },
  {
    id: 6,
    name: "Chat App",
    languages: ["JavaScript", "React"],
    languagesIcons: ["fab fa-js", "fab fa-react"],
    source: "https://github.com/Caronat/CRUD-Chat",
    info: "Application permettant d'échanger des messages et de commenter les messages des autres utilisateurs.",
    picture: "./media/chat.JPG",
    link: "https://www.chat.antonycaron.fr/",
  },
];
